server:
  port: 2001

spring:
  application:
    name: server-center
  profiles: #合并配置中心，测试方便
    active: native    #激活本地文件系统
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config   #本地配置代替git

# 关闭保护模式
# 主机名
# 不注册,不拉取
eureka:
  server:
    enable-self-preservation: false # 保护模式
  instance:
    hostname: eurekva
    prefer-ip-address: true
  client:
    register-with-eureka: true  #配置中心需要注册
    fetch-registry: false
    service-url:
      defaultZone: http://eurekava:2001/eureka

#引入日志信息
logging:
  level:
    com.jt.mapper: debug
