server:
  port: 2001

# 关闭保护模式
# 主机名
# 不注册,不拉取
eureka:
  instance:
    hostname: eurekva
    prefer-ip-address: true
  client:
    register-with-eureka: true  #配置中心需要注册
    fetch-registry: true
    service-url:
      defaultZone: http://eurekavb:2002/eureka

