#服务端
server:
    port: 8086

spring:
    application:
        name: user-work
    servlet:
        multipart:
            max-request-size: 100MB
            max-file-size: 50MB

csa:
    filepath: E:/base/boke/  #上传图片位置