server:
  port: 6001

spring:
  application:
    name: zuul

#zuul:
#  retryable: true
#  #zuul 一般是用来作为网关服务开发，zuul默认对转发的request，会把header清空，为了传递原始的header信息到最终的微服务
#  #需要忽略的头部信息，不在传播到其他服务
#  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
#  ignored-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials