#ribbon配置
ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 3000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0

# 设置不重试
spring:
    cloud:
        loadbalancer:
            retry:
                enabled: false

#hystrix配置
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 15000

#feign配置
feign:
    hystrix:
        enabled: true



