#服务端
server:
    port: 8083

spring:
    application:
        name: boke-keeper
    profiles:
        include: database,feign,redis

#日志配置
logging:
    level:
        root: warn
        csa.stu.app: debug
        org.springframework: info
        org.apache.ibatis: debug
        com.alibaba.druid: debug
    pattern:
        console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"



