#业务微服务基础配置

spring:
    cloud:
        config:
            override-none: true
    servlet:
        multipart:
            max-request-size: 100MB
            max-file-size: 50MB

#ribbon配置
ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 3000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0

#hystrix配置
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 15000

#feign配置
feign:
    hystrix:
        enabled: true
