#服务端
server:
    port: 9000

spring:
    application:
        name: front
    profiles:
        include: feign,redis
    cloud:
        config:
            override-none: true
    servlet:
        multipart:
            max-request-size: 100MB
            max-file-size: 50MB