server:
  port: 6001

spring:
  application:
    name: config-center
  profiles:
    active: native    #激活本地文件系统
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config   #本地配置代替git


#日志配置
logging:
  level:
    root: warn
    csa.stu.app: info
    org.springframework: info
    org.apache.ibatis: debug
    com.alibaba.druid: debug
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://eurekava:2001/eureka  #,http://eurekavb:2002/eureka
