spring:
  cloud:
    config:
      override-none: true

zuul:
  retryable: true
  #zuul 一般是用来作为网关服务开发，zuul默认对转发的request，会把header清空，为了传递原始的header信息到最终的微服务
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
  ignored-headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials

#ribbon配置
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2

#hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

#feign配置
feign:
  hystrix:
    enabled: true
