
spring:
  cloud:
    config:
      override-none: true

zuul:
  retryable: true

#ribbon配置
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2

#hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#feign配置
feign:
  hystrix:
    enabled: true
